spring:
  application:
    name: maxxGlobal
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres
    username: postgres.skeldspwntygaqfojncq
    password: JyEPBEaDUsSnkQ7a
    hikari:
      ssl-mode: require

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        statement_cache_size: 0
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # File Upload Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB          # Tek dosya için maksimum boyut
      max-request-size: 50MB      # Toplam request boyutu (10 resim x 5MB)
      file-size-threshold: 2KB    # Memory'de tutulacak minimum boyut

application:
  security:
    jwt:
      secret-key: ZmFrZXNlY3JldGtleWZvcm1heGdsb2JhbA==
      expiration: 86400000  # 1 gün (ms cinsinden)

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: false
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
  show-actuator: false
  use-management-port: false
  cache:
    disabled: false

# Application Info
app:
  name: "Ortopedi Sipariş Sistemi"
  description: "Ortopedi ameliyat malzemeleri için B2B sipariş yönetim sistemi"
  version: "1.0.0"

  # File Storage Configuration
  file:
    upload-dir: "uploads"         # Ana upload klasörü
    product-images-dir: "products" # Product resimleri için alt klasör
    base-url: "http://localhost:8080" # Resim URL'leri için base URL
    allowed-extensions: ["jpg", "jpeg", "png", "gif", "webp"]
    max-image-size: 5242880      # 5MB in bytes

# Actuator endpoints (opsiyonel - monitoring için)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized