spring:
  application:
    name: maxxGlobal
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres?prepareThreshold=0&ssl=true&sslmode=require
    username: postgres.skeldspwntygaqfojncq
    password: JyEPBEaDUsSnkQ7a
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

    database: postgresql
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 50MB
      file-size-threshold: 2KB

application:
  security:
    jwt:
      secret-key: ZmFrZXNlY3JldGtleWZvcm1heGdsb2JhbA==
      expiration: 86400000

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

app:
  name: "Ortopedi Sipariş Sistemi"
  description: "Ortopedi ameliyat malzemeleri için B2B sipariş yönetim sistemi"
  version: "1.0.0"
  file:
    upload-dir: "uploads"
    product-images-dir: "products"
    base-url: "http://localhost:8080"
    allowed-extensions: ["jpg", "jpeg", "png", "gif", "webp"]
    max-image-size: 5242880
  excel:
    max-rows: 10000  # Maksimum işlenebilir satır sayısı
    batch-size: 100  # Batch insert boyutu
    date-format: "dd.MM.yyyy HH:mm"
    supported-currencies: [ "TRY", "USD", "EUR" ]
# Logging configuration for Excel operations
logging:
  level:
    com.maxx_global.service.ProductPriceExcelService: INFO
    org.apache.poi: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized