spring:
  application:
    name: maxxGlobal
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres
    username: postgres.skeldspwntygaqfojncq
    password: JyEPBEaDUsSnkQ7a
    hikari:
      ssl-mode: require

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        statement_cache_size: 0
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: ZmFrZXNlY3JldGtleWZvcm1heGdsb2JhbA==
      expiration: 86400000  # 1 gün (ms cinsinden)

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: false
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
  show-actuator: false
  use-management-port: false
  cache:
    disabled: false

# Application Info
app:
  name: "Ortopedi Sipariş Sistemi"
  description: "Ortopedi ameliyat malzemeleri için B2B sipariş yönetim sistemi"
  version: "1.0.0"

# Actuator endpoints (opsiyonel - monitoring için)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized